repos:
# 基本格式检查
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # 文件格式检查
    - id: check-yaml       # 检查YAML文件格式
    - id: check-json       # 检查JSON文件格式
    - id: check-toml       # 检查TOML文件格式
    - id: check-xml        # 检查XML文件格式
    - id: check-ast        # 检查Python语法错误
    # 安全检查
    - id: detect-private-key      # 检查私钥泄露
    - id: detect-aws-credentials  # 检查AWS凭证泄露
    # 代码风格和问题检查
    - id: trailing-whitespace     # 检查行尾空格
    - id: end-of-file-fixer       # 检查文件结尾有一个空行
    - id: check-merge-conflict    # 检查合并冲突标记
    - id: debug-statements        # 检查调试语句
    - id: check-added-large-files # 检查大文件 (默认500kB)
      args: ['--maxkb=1000']      # 增加到1MB限制

# Python代码质量工具 (Ruff替代了多个工具)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.13
  hooks:
    # 运行linter (替代flake8, pylint等)
    - id: ruff-check
      args: [
        "--fix",
        "--select=E,F,W,I,N,UP,B,S,BLE,COM,C4,DTZ,T10,EM,FA,ISC,ICN,PT,Q,RSE,RET,SIM,TID,ARG,ERA,PD,PGH,PL,TRY,NPY,RUF",
        "--ignore=E203,E501"
      ]
    # 运行格式化器 (替代black和isort)
    - id: ruff-format

# 类型检查
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.0
  hooks:
    - id: mypy
      # 使用pyproject.toml中的配置
      args: []
      additional_dependencies:
        - "types-PyYAML>=6.0.0"
        - "types-requests>=2.31.0"

# 安全漏洞检查
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.3
  hooks:
    - id: bandit
      args: [
        "--recursive",
        "--exclude", "tests,docs,scripts/templates",
        "--configfile", "pyproject.toml"
      ]
      additional_dependencies: ["bandit[toml]>=1.7.5"]

# 检查文档字符串
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
    - id: pydocstyle
      # 使用pyproject.toml中ruff的pydocstyle配置
      exclude: "tests/|scripts/templates/|docs/"
      additional_dependencies: ["tomli>=2.0.0"]
