site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.project_short_description }}
site_author: {{ cookiecutter.full_name }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
repo_name: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
edit_uri: edit/master/docs/

# 导航结构
nav:
  - 首页: index.md
  - 安装: installation.md
  - 使用指南: usage.md
  - 项目结构: project_structure.md
  - 统一安装脚本: setup_script.md
  - 工具库: utils.md
  - 版本管理: version.md
  - 开发指南: developer_guide.md
  - Dependabot: dependabot.md
  - Docker: docker.md
  - API参考:
    - api/index.md
  - 贡献指南: contributing.md
  - 贡献者: authors.md
  - 更新日志: history.md

# 主题配置
theme:
  name: material
  language: zh
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.action.edit

# 扩展
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# 插件
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: false
            show_if_no_docstring: false
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

# 额外的CSS和JavaScript
extra_css:
  - css/extra.css

# 版权信息
copyright: "Copyright &copy; {% now 'local', '%Y' %} {{ cookiecutter.full_name }}"

# 社交链接
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
