# GitHub CI build pipeline
name: Cookie Cutter CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          if  [ -f requirements.txt ]; then pip install -r requirements_dev.txt; fi

      - name: Run Tests and generate coverage report
        run: |
          coverage run -m pytest
      - name: Archive code coverage html report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: src/htmlcov
      - name: Run package creation
        run: |
          python -m pip install --user --upgrade build
          python -m build
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: cookie-cutter
          path: src/dist
